eureka:
  client:
    service-url:
      default-zone: http://${other.eureka.host}:${other.eureka.port}/eureka

---
spring:
  application:
    name: eureka-1
  config:
    activate:
      on-profile: eureka-1

server:
  port: 8761
eureka:
  instance:
    hostname: eureka1.tacocloud.com
other:
  eureka:
    host: eureka2.tacocloud.com
    port: 8761

---
spring:
  application:
    name: eureka-2
  config:
    activate:
      on-profile: eureka-2

server:
  port: 8762
eureka:
  instance:
    hostname: eureka2.tacocloud.com
other:
  eureka:
    host: eureka1.tacocloud.com
    port: 8762