eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${other.eureka.port}/eureka

---
spring:
  application:
    name: eureka-1
  config:
    activate:
      on-profile: eureka-1

server:
  port: 8761

other:
  eureka:
    port: 8762

---
spring:
  application:
    name: eureka-2
  config:
    activate:
      on-profile: eureka-2

server:
  port: 8762

other:
  eureka:
    port: 8761