server:
  port: 0

spring:
  application:
    name: ingredient-service

eureka:
  client:
    service-url:

      default-zone: http://eureka1.tacocloud.com:8761/eureka/, http://eureka2.tacocloud.com:8762/eureka/

